### ISSUE TITLE
calling apply instead of drop doesn't result in the modifications being applied to the player.

### ISSUE THREAD

**Issue by mainrs** [MinecraftPhi/MinecraftPhi-modules#14]
The wiki states:

> 4. Call phi.modifyinv:apply/* as the player, or phi.modifyinv:drop/*
>
>   This will save the modified slots to the player when using apply, or drop the slots at >   the current position and clear those slots in the player's inventory when using drop

Maybe I am misunderstanding the entry, but it seems like `apply` should save the modified items to the players inventory. They both sound the same too me :(

**Comment by vdvman1** [comment]
`apply` should replace the specified section of the contents of the player's inventory with the contents of the shulker box
`drop` should drop the items in the shulker box as item entities at the context position and remove the specified section from the contents of the player's inventory
Do these not behave as expected? Or are you saying that the wiki entry is ambiguous?

**Comment by mainrs** [comment]
They don't behave as expected. I noticed that I do not get a message during world initialization like the readme states that ensures that the needed chunk at -30000000 is force loaded. 

Maybe I am using this library the wrong way though. I have the following code that gets executed:

```mcfunction
function phi.modifyinv:setup/whole_inventory
function phi.modifyinv:load/hotbar
data modify block -30000000 0 1602 Items[{id:"minecraft:iron_ingot",tag:{isMagnet:1b}}].tag.display.Lore set value ['{"text":"Attracts items within a 6 block radius (Off-Hand)","color":"gray"}']
function phi.modifyinv:apply/hotbar
```

The function gets called as a reward function of an advancements. The criteria that triggers it is an `inventory_changed` trigger that looks for an `iron_ingot` with the nbt tag `isMagnet`.

The above lines, if run manually using the chat, fail with the `data modify...` call. The error message is `That position is not loaded`.

**Comment by vdvman1** [comment]
Sounds like the chunk didn't end up getting forceloaded. Does running `function phi.core:resetup` forceload the chunk correctly?
Also, are there any errors in the game log?

**Comment by mainrs** [comment]
I think I found the issue! I had Fabric installed. After disabling it the data pack works fine. Quite strange though, I thought only Forge had issues with their `tick` function not being implemented right...

Sorry for the inconvenience!

**Comment by vdvman1** [comment]
No problem. Thankyou for letting me know that Fabric also causes problems.

**Comment by mainrs** [comment]
I did some more digging:

__MutliMC Version__: 0.6.7-1375
__Java Version:__ jdk-8.0.232.09-hotspot (bundled version)
__Main Class:__ net.fabricmc.loader.launch.knot.KnotClient
__Fabric Loader:__ fabricloader@0.6.3+build.168
__Fabric API:__ fabric-api-0.4.1+build.245-1.14

As soon as I enable the Fabric API, the data pack fails to work because the chunks don't get force-loaded.

<details><summary>Log lines that might be relevant</summary>

__[00:00:56]__ [main/INFO]: Loading for game Minecraft 1.14.4
__[00:00:59]__ [main/INFO]: [FabricLoader] Loading 30 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.6.3+build.168, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, fabric-biomes-v1@0.1.0+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, fabric-rendering-data-attachment-v1@0.1.1+c877038942, fabric-resource-loader-v0@0.1.3+591e97ae42, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric@0.4.1+build.245-1.14, fabric-particles-v1@0.1.1+c877038942, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-models-v0@0.1.0+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42
__[00:00:59]__ [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/me/Documents/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
__[00:01:12]__ [main/INFO]: Compatibility level set to JAVA_8
__[00:01:52]__ [Server thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
__[00:01:52]__ [Server thread/INFO]: Found new data pack fabric/fabric-mining-levels-v0, loading it automatically
__[00:01:52]__ [Server thread/INFO]: Reloading ResourceManager: Default, phi.core.zip, phi.modifyinv.zip, zerotask-utils, quality_armor, Fabric Mining Levels (v0)
__[00:01:53]__ [Server thread/INFO]: Loaded 6 recipes
__[00:01:53]__ [Server thread/INFO]: Loaded 71 custom command functions
__[00:01:53]__ [Server thread/INFO]: Loaded 814 advancements
__[00:01:53]__ [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
__[00:01:54]__ [main/INFO]: Preparing spawn area: 0%
__[00:01:54]__ [main/INFO]: Preparing spawn area: 0%
__[00:01:54]__ [main/INFO]: Preparing spawn area: 82%
__[00:01:54]__ [main/INFO]: Time elapsed: 1118 ms
</details>

__EDIT:__ Wow, something really, really strange happened. I left the world that this data pack and mine are used in. I re-logged and the item that I modified actually changed. The lore got updated even though that it didn't work beforehand. It kind of "updated" during world save...? However, the enchanting that the item had as well as the custom name, got removed. As if the changes that I made to the item did not get merged but super-seeded and replaced everything else.

__EDIT2:__ OK, the item does update __but__ the client doesn't change the lore text. I couldn't see any cause on why it wouldn't work so I double checked with `data get entity SirWindfield SelectedItem` and the item has the updated NBT data on it. The client just doesn't update the tooltip displayed until I open a chest or another block with an UI. Opening your own inventory doesn't force a tooltip update...

It also happens in a pure vanilla environment. So maybe the client doesn't update the tooltip since it things that nothing changed in the inventory?
